apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: qz1v3vw0o-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:ae576eb583c952572b8d6cfdfb1e7c466e1ae028@sha256:709e258c4a9740b5acb1c4ee4f322cd2d051cef791d070f771b448ec20c91389
          name: container-image
